### ISSUE TITLE
More operations?

### ISSUE THREAD

**Issue by wshager** [bionut/js-persistent-vector#1]
Any chance you'll add more operations, like slice?

**Comment by wshager** [comment]
I added something in my fork. I only found something suitable in FB's immutable.js that doesn't prevent GC. There may be some overlap, so I'll clean it up good.

**Comment by wshager** [comment]
Good work by the way, this seems to outperform most other implementations.

**Comment by bionut** [comment]
If I remember correctly, this is a conversion from [hyPiRion/pvec-perf](https://github.com/hyPiRion/pvec-perf/tree/master/pvec/src/com/hypirion/pvec). There is some very good content regarding immutable data structures on his [website](http://hypirion.com). I strongly recommend his [thesis](http://hypirion.com/musings/thesis)

**Comment by wshager** [comment]
@bionut Ok I know it, yes. I was planning to read his write-up on persistent vectors on his blog tonight :) thanks
